services:
  # PostgreSQL Database - Essential for A2A protocol
  postgres:
    image: postgres:16-alpine  # Much smaller than pgvector image
    container_name: pygent_postgres_minimal
    environment:
      POSTGRES_DB: pygent_factory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres 
      -c log_statement=all
      -c log_destination=stderr
      -c logging_collector=on
      -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pygent_factory"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pygent_network

  # Redis for caching - Lightweight
  redis:
    image: redis:7-alpine
    container_name: pygent_redis_minimal
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pygent_network

  # PyGent Factory API with A2A Protocol
  pygent-api:
    build:
      context: .
      target: production
    container_name: pygent-factory-api-minimal
    ports:
      - "8080:8000"  # Main API
      - "8006:8006"  # A2A MCP Server
    environment:
      - PYGENT_ENV=production
      - PYGENT_LOG_LEVEL=INFO
      - PYGENT_GPU_ENABLED=false
      - PYGENT_API_PORT=8000
      - PYGENT_MAX_WORKERS=2  # Reduced for minimal deployment
      - A2A_ENABLED=true
      - A2A_BASE_URL=http://localhost:8000
      - A2A_MCP_PORT=8006
      - A2A_DISCOVERY_ENABLED=true
      - A2A_SECURITY_ENABLED=true
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pygent_factory
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - postgres
      - redis
    networks:
      - pygent_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  pygent_network:
    driver: bridge
