global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # PyGent Factory main application
  - job_name: 'pygent-factory'
    static_configs:
      - targets: ['pygent-factory:8002']
    scrape_interval: 10s
    metrics_path: /metrics

  # GPU metrics (if nvidia-dcgm-exporter is available)
  - job_name: 'gpu-metrics'
    static_configs:
      - targets: ['pygent-factory:9400']
    scrape_interval: 5s
    metrics_path: /metrics

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Docker daemon metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s

  # Node exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s
