
from flask import Flask, jsonify

app = Flask(__name__)

@app.route("/")
def home():
    return """
    <h1>Agent-Generated Dashboard</h1>
    <p>This interface was created by AI agents!</p>
    <button onclick="loadData()">Load Data</button>
    <div id="results"></div>
    
    <script>
    function loadData() {
        fetch('/api/data')
            .then(r => r.json())
            .then(data => {
                document.getElementById('results').innerHTML = 
                    '<pre>' + JSON.stringify(data, null, 2) + '</pre>';
            });
    }
    </script>
    """

@app.route("/api/data")
def api_data():
    return jsonify({
        "message": "Data processed by AI-generated code",
        "trends": ["Sales increasing", "Customer satisfaction improving"],
        "status": "Generated by agent swarm"
    })

if __name__ == "__main__":
    app.run(port=5000)
