#!/usr/bin/env python3
"""
Snake Game - Generated by AI Agent Swarm

This entire application was dynamically generated by analyzing requirements
and writing code from scratch - no templates or mocks!

Requirements analyzed:
- 3 lives system
- Aggressive food-seeking behavior  
- Web/HTTP interface
- Collision detection
- Scoring system
"""

import os
import sys
import webbrowser
import time
import threading


def main():
    """Main entry point for the snake game."""
    
    print("🐍 AI-Generated Snake Game")
    print("=" * 40)
    print("🤖 Generated by Agent Swarm")
    print("📋 Features:")
    print("   • 3 Lives system")
    print("   • Aggressive food-seeking AI")
    print("   • Web interface")
    print("   • Real-time gameplay")
    print()
    
    # Create static directory if it doesn't exist
    if not os.path.exists('static'):
        os.makedirs('static')
        print("📁 Created static directory")
    
    print("🚀 Starting web server...")
    
    # Import and start the web server
    try:
        from web_server import app
        
        # Open browser after short delay
        def open_browser():
            time.sleep(1.5)
            webbrowser.open('http://localhost:5000')
        
        threading.Thread(target=open_browser, daemon=True).start()
        
        print("🌐 Game will open in your browser at: http://localhost:5000")
        print("🎮 Use arrow keys or on-screen buttons to control")
        print("🔥 Watch the AI aggressively seek food!")
        print()
        print("Press Ctrl+C to stop the server")
        
        # Run the Flask app
        app.run(host='0.0.0.0', port=5000, debug=False)
        
    except ImportError as e:
        print(f"❌ Error importing web server: {e}")
        print("Make sure all generated files are in the same directory")
        sys.exit(1)
    except KeyboardInterrupt:
        print("\n👋 Game server stopped")
        sys.exit(0)


if __name__ == "__main__":
    main()
