name: Minimal CI/CD Test

on:
  push:
    branches: [ master, main, minimal-workflow-test ]
  pull_request:
    branches: [ master, main ]

jobs:
  # Minimal Test Job - Observer Cycle Breaking
  minimal-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test minimal workflow
      run: echo "✅ Minimal workflow startup successful - Observer cycle broken"
