name: Minimal CI/CD Test

on:
  push:
    branches: [ master, main, minimal-workflow-test ]
  pull_request:
    branches: [ master, main ]

env:
  # UTF-8 Environment Configuration - Observer Phase 2 Restoration
  PYTHONIOENCODING: utf-8
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8
  PYTHON_VERSION: '3.11'
  # Observer Enhanced Debugging - Phase 2.3
  ACTIONS_STEP_DEBUG: true

jobs:
  # Python Backend Test - Observer Phase 2 Dependency Restoration
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python tests
      env:
        PYTHONIOENCODING: utf-8
        LANG: en_US.UTF-8
        LC_ALL: en_US.UTF-8
      run: |
        python --version
        pip list
        echo "✅ Running basic tests - Observer Phase 2.3"
        # Run basic import tests
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import os; print(f'UTF-8 encoding: {os.environ.get(\"PYTHONIOENCODING\", \"not set\")}')"
        echo "✅ Basic testing framework restored - Observer Phase 2.3"
