name: Minimal CI/CD Test

on:
  push:
    branches: [ master, main, minimal-workflow-test ]
  pull_request:
    branches: [ master, main ]

env:
  # UTF-8 Environment Configuration - Observer Phase 2 Restoration
  PYTHONIOENCODING: utf-8
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

jobs:
  # Minimal Test Job - Observer Cycle Breaking
  minimal-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test minimal workflow
      run: echo "✅ Minimal workflow startup successful - Observer cycle broken"
